"""
Django settings for killshill project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
SECRET_KEY = config('SECRET_KEY', default='django-insecure-tr69*6xw+t55-vw@j&0e&q=e4-=44yk%y9!qk!1&v_yq8cn2)2')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Supabase Configuration
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_KEY = config('SUPABASE_KEY', default='')
DATABASE_URL = config('DATABASE_URL', default='')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter_oauth2',
    
    # Local apps
    'authentication',
    'influencers',
    'dashboard',
    'api',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'killshill.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.pending_submissions_count',
                'dashboard.context_processors.unread_notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'killshill.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': 'prefer',  # Changed from 'require' to handle cert issues
            'connect_timeout': 30,
            'application_name': 'killshill_django',
            'options': '-c default_transaction_isolation=read_committed',
            # Handle SSL certificate issues with Supabase
            'sslcert': None,
            'sslkey': None, 
            'sslrootcert': None,
        },
        'CONN_MAX_AGE': 600,  # 10 minutes connection reuse
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SECRET_KEY', default=SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# OAuth Configuration  
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'VERIFIED_EMAIL': True,
    },
    'twitter_oauth2': {
        'SCOPE': [
            'tweet.read',
            'users.read',
        ],
        'APP': {
            'client_id': config('TWITTER_OAUTH2_CLIENT_ID', default=''),
            'secret': config('TWITTER_OAUTH2_CLIENT_SECRET', default=''),
        }
    }
}

# Account settings (Updated for django-allauth v65+)
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_LOGIN_ON_GET = True

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_BOT_USERNAME = config('TELEGRAM_BOT_USERNAME', default='')

# Auto-Approval Configuration
ENABLE_AUTO_APPROVAL = config('ENABLE_AUTO_APPROVAL', default=True, cast=bool)
AUTO_APPROVAL_MIN_CONFIDENCE = config('AUTO_APPROVAL_MIN_CONFIDENCE', default=70, cast=int)
AUTO_APPROVAL_MIN_FOLLOWERS = config('AUTO_APPROVAL_MIN_FOLLOWERS', default=1000, cast=int)
AUTO_APPROVAL_MAX_VARIANCE = config('AUTO_APPROVAL_MAX_VARIANCE', default=0.3, cast=float)

# Platform API Keys
TWITTER_BEARER_TOKEN = config('TWITTER_BEARER_TOKEN', default='')
TWITTER_API_KEY = config('TWITTER_API_KEY', default='')
TWITTER_API_SECRET = config('TWITTER_API_SECRET', default='')
YOUTUBE_API_KEY = config('YOUTUBE_API_KEY', default='')
INSTAGRAM_ACCESS_TOKEN = config('INSTAGRAM_ACCESS_TOKEN', default='')
TIKTOK_ACCESS_TOKEN = config('TIKTOK_ACCESS_TOKEN', default='')

# Apify Integration
APIFY_TOKEN = config('APIFY_TOKEN', default='')

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development - prints to console
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
# EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Notification Settings
SEND_BATCH_NOTIFICATIONS = config('SEND_BATCH_NOTIFICATIONS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@killshill.com')

# Rate Limiting
AUTO_APPROVAL_RATE_LIMIT = {
    'requests_per_minute': config('AUTO_APPROVAL_REQUESTS_PER_MINUTE', default=60, cast=int),
    'requests_per_hour': config('AUTO_APPROVAL_REQUESTS_PER_HOUR', default=1000, cast=int),
    'concurrent_processing': config('AUTO_APPROVAL_CONCURRENT_PROCESSING', default=5, cast=int),
}

# Security Settings
AUTO_APPROVAL_SECURITY = {
    'max_submissions_per_user_per_day': config('AUTO_APPROVAL_MAX_SUBMISSIONS_PER_DAY', default=10, cast=int),
    'require_email_verification': config('AUTO_APPROVAL_REQUIRE_EMAIL_VERIFICATION', default=True, cast=bool),
    'blacklisted_domains': [
        'example-spam-domain.com',
        'suspicious-site.net',
    ],
    'min_account_age_days': config('AUTO_APPROVAL_MIN_ACCOUNT_AGE_DAYS', default=1, cast=int),
}

# Verification Weights
VERIFICATION_WEIGHTS = {
    'verification_confidence': 0.4,
    'follower_accuracy': 0.25,
    'account_age': 0.15,
    'platform_verification': 0.1,
    'engagement_quality': 0.1
}

# Platform-specific configurations
PLATFORM_CONFIGS = {
    'Twitter': {
        'min_confidence': 60,
        'min_followers': 500,
        'max_variance': 0.3,
        'require_verification': False,
    },
    'YouTube': {
        'min_confidence': 65,
        'min_followers': 1000,
        'max_variance': 0.25,
        'require_verification': False,
    },
    'Telegram': {
        'min_confidence': 50,
        'min_followers': 100,
        'max_variance': 0.4,
        'require_verification': False,
    },
    'TikTok': {
        'min_confidence': 60,
        'min_followers': 10000,
        'max_variance': 0.3,
        'require_verification': False,
    },
    'Instagram': {
        'min_confidence': 65,
        'min_followers': 1000,
        'max_variance': 0.3,
        'require_verification': False,
    },
    'Discord': {
        'min_confidence': 40,
        'min_followers': 100,
        'max_variance': 0.5,
        'require_verification': False,
    },
}

# Jazzmin Admin UI Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Killshill Admin",
    "site_header": "Killshill Administration",
    "site_brand": "Killshill",
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to Killshill Admin Panel",
    "copyright": "Killshill Ltd",
    "search_model": ["auth.User", "influencers.Influencer", "influencers.TradeCall"],
    "user_avatar": None,
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Dashboard", "url": "/dashboard/", "new_window": True},
        {"model": "auth.User"},
        {"app": "influencers"},
    ],
    
    # User Menu
    "usermenu_links": [
        {"name": "Dashboard", "url": "/dashboard/", "new_window": True},
        {"model": "auth.user"}
    ],
    
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "influencers", "dashboard", "api"],
    
    # Custom Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "influencers": "fas fa-star",
        "influencers.Influencer": "fas fa-user-star",
        "influencers.Asset": "fas fa-coins",
        "influencers.TradeCall": "fas fa-chart-line",
        "dashboard": "fas fa-tachometer-alt",
        "api": "fas fa-code",
    },
    
    # Default Icons
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Related Modal
    "related_modal_active": False,
    
    # Custom CSS/JS
    "custom_css": None,
    "custom_js": None,
    
    # Show/Hide actions
    "show_ui_builder": False,
    
    # Change view
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
    # Language chooser
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'auto_approval_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'auto_approval.log',
            'maxBytes': 15728640,  # 15MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'dashboard.services': {
            'handlers': ['auto_approval_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'dashboard.tasks': {
            'handlers': ['auto_approval_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Additional Database Connection Stability Settings
import os
os.environ.setdefault('DJANGO_DB_CONN_MAX_AGE', '600')

# Database connection timeout and retry settings
DATABASE_CONNECTION_POOLING = {
    'MAX_CONNS': 20,
    'MIN_CONNS': 5,
    'CONNECTION_TIMEOUT': 30,
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 1,
}

# Ensure logs directory exists
os.makedirs(BASE_DIR / 'logs', exist_ok=True)
