# Generated by Django 5.2.7 on 2025-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=255)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=255, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('change24hr', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('influencer_id', models.BigAutoField(db_column='influencer_id', primary_key=True, serialize=False)),
                ('channel_name', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'influencer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('signal', models.TextField(blank=True, null=True)),
                ('entry_price', models.CharField(blank=True, max_length=255, null=True)),
                ('assumed_entry_price', models.FloatField(blank=True, null=True)),
                ('stoploss_price', models.FloatField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('target_first', models.FloatField(blank=True, null=True)),
                ('target_second', models.FloatField(blank=True, null=True)),
                ('target_third', models.FloatField(blank=True, null=True)),
                ('target_fourth', models.FloatField(blank=True, null=True)),
                ('timeframe', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('stoploss_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('target_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('assumed_target', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_workflow_started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trade_call',
                'managed': False,
            },
        ),
    ]
