# Generated by Django 5.2.7 on 2025-11-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfluencer',
            fields=[
                ('web_influencer_id', models.BigAutoField(db_column='web_influencer_id', primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('platform_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'web_influencer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebInfluencerDetails',
            fields=[
                ('web_influencer_details_id', models.BigAutoField(db_column='web_influencer_details_id', primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=500, null=True)),
                ('recommendation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'web_influencer_details',
                'managed': False,
            },
        ),
    ]
