# Generated by Django 5.2.7 on 2025-10-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('auto_approved', models.BooleanField(default=False)),
                ('approval_score', models.IntegerField(default=0, help_text='Auto-approval score calculated')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('YouTube', 'YouTube'), ('Discord', 'Discord'), ('Instagram', 'Instagram')], max_length=20)),
                ('channel_name', models.CharField(help_text='Channel/Account name', max_length=255)),
                ('author_name', models.CharField(blank=True, help_text='Real name if known', max_length=255)),
                ('url', models.URLField(help_text='Profile URL')),
                ('follower_count', models.PositiveIntegerField(default=0, help_text='Number of followers/subscribers')),
                ('category', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('defi', 'DeFi & Web3'), ('nft', 'NFTs'), ('technical', 'Technical Analysis'), ('day_trading', 'Day Trading'), ('swing', 'Swing Trading'), ('long_term', 'Long-term Investment')], max_length=50)),
                ('trading_style', models.CharField(blank=True, choices=[('scalping', 'Scalping'), ('day_trading', 'Day Trading'), ('swing', 'Swing Trading'), ('position', 'Position Trading'), ('mixed', 'Mixed Approach')], max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Background and description')),
                ('evidence', models.TextField(blank=True, help_text='Evidence of performance')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'influencer_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='influencersubmission',
            index=models.Index(fields=['status', 'created_at'], name='dashboard_in_status_f4b7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='influencersubmission',
            index=models.Index(fields=['submitted_by', 'status'], name='dashboard_in_submitt_1d7c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='influencersubmission',
            index=models.Index(fields=['auto_approved'], name='dashboard_in_auto_ap_7b6a8c_idx'),
        ),
    ]
