# Generated by Django 5.2.7 on 2025-10-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20251013_1822'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='influencersubmission',
            new_name='influencer__status_b545b4_idx',
            old_name='dashboard_in_status_f4b7b1_idx',
        ),
        migrations.RenameIndex(
            model_name='influencersubmission',
            new_name='influencer__submitt_21d89e_idx',
            old_name='dashboard_in_submitt_1d7c8b_idx',
        ),
        migrations.RenameIndex(
            model_name='influencersubmission',
            new_name='influencer__auto_ap_87592e_idx',
            old_name='dashboard_in_auto_ap_7b6a8c_idx',
        ),
    ]
