# Generated by Django 5.2.7 on 2025-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_dashboard_in_status_f4b7b1_idx_influencer__status_b545b4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencersubmission',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile avatar URL'),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='bio',
            field=models.TextField(blank=True, help_text='Profile bio from platform'),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name from platform', max_length=255),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='extracted_at',
            field=models.FloatField(blank=True, help_text='Timestamp when data was extracted', null=True),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='following',
            field=models.PositiveIntegerField(default=0, help_text='Number of accounts following'),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='meets_criteria',
            field=models.BooleanField(default=False, help_text='Meets auto-approval criteria'),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='mock_data',
            field=models.BooleanField(default=False, help_text='Whether data is mocked'),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='posts_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of posts/videos'),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='username',
            field=models.CharField(blank=True, help_text='Platform username', max_length=255),
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='verified',
            field=models.BooleanField(default=False, help_text='Platform verified status'),
        ),
        migrations.AlterField(
            model_name='influencersubmission',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
