# Generated by Django 5.2.7 on 2025-11-10 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_influencersubmission_avatar_url_and_more'),
        ('influencers', '0002_webinfluencer_webinfluencerdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('call', 'Trade Call'), ('profile', 'Influencer Profile')], max_length=20)),
                ('reason', models.CharField(choices=[('fake_data', 'Fake or Manipulated Data'), ('spam', 'Spam or Promotional Content'), ('manipulation', 'Market Manipulation'), ('misleading', 'Misleading Information'), ('duplicate', 'Duplicate Profile'), ('offensive', 'Offensive Content'), ('scam', 'Potential Scam'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes on resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('influencer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='influencers.influencer')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('trade_call', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='influencers.tradecall')),
            ],
            options={
                'db_table': 'abuse_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='abuse_repor_status_3bcfb2_idx'), models.Index(fields=['report_type', 'status'], name='abuse_repor_report__7b8b37_idx'), models.Index(fields=['reporter'], name='abuse_repor_reporte_a22ed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this influencer')),
                ('influencer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='influencers.influencer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='watchlist_user_id_232a00_idx')],
                'unique_together': {('user', 'influencer')},
            },
        ),
    ]
