# Generated by Django 5.2.7 on 2025-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_abusereport_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencersubmission',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
