# Generated by Django 5.2.7 on 2025-11-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_influencersubmission_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencersubmission',
            name='manual_follower_count',
            field=models.PositiveIntegerField(default=0, help_text='User provided follower snapshot'),
        ),
    ]
