# Generated by Django 5.2.7 on 2025-11-25 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_influencersubmission_manual_follower_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text="Type of notification: 'call' or 'submission'", max_length=50)),
                ('notification_id', models.CharField(help_text='Unique identifier for the notification', max_length=255)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_read',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_13026b_idx'), models.Index(fields=['user', 'notification_id'], name='notificatio_user_id_238de6_idx')],
                'unique_together': {('user', 'notification_id')},
            },
        ),
    ]
