# Generated by Django 5.2.7 on 2025-11-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_notification_read_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencersubmission',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='influencersubmission',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='influencersubmission',
            name='trading_style',
        ),
        migrations.AddField(
            model_name='influencersubmission',
            name='categories',
            field=models.JSONField(default=list, help_text='Multiple categories supported: crypto, stocks, forex'),
        ),
        migrations.AlterField(
            model_name='influencersubmission',
            name='category',
            field=models.CharField(blank=True, choices=[('crypto', 'Cryptocurrency'), ('stocks', 'Stocks'), ('forex', 'Forex')], help_text='Primary category (for backward compatibility)', max_length=50),
        ),
    ]
