# Generated by Django 5.2.7 on 2025-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_influencersubmission_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencersubmission',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile avatar URL', max_length=500),
        ),
    ]
