# Generated by Django 5.2.7 on 2025-11-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_fix_avatar_url_length'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Add follower_count column to influencer table
            sql="ALTER TABLE influencer ADD COLUMN follower_count INTEGER DEFAULT 0;",
            # Reverse SQL - Remove follower_count column
            reverse_sql="ALTER TABLE influencer DROP COLUMN follower_count;",
        ),
    ]
