# Generated by Django 5.2.7 on 2025-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Add missing columns to existing user_profile table
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'user';",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS role;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS location VARCHAR(100) DEFAULT '';",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS location;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS website VARCHAR(200);",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS website;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT true;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS email_notifications;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS push_notifications BOOLEAN DEFAULT true;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS push_notifications;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS newsletter_subscription BOOLEAN DEFAULT false;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS newsletter_subscription;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS is_verified;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT false;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS is_premium;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS premium_expires_at TIMESTAMP;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS premium_expires_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS google_connected BOOLEAN DEFAULT false;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS google_connected;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS twitter_connected BOOLEAN DEFAULT false;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS twitter_connected;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS telegram_connected BOOLEAN DEFAULT false;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS telegram_connected;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS telegram_user_id VARCHAR(50);",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS telegram_user_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS telegram_username VARCHAR(100);",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS telegram_username;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS last_login_ip INET;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS last_login_ip;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS login_count INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE user_profile DROP COLUMN IF EXISTS login_count;"
        ),
    ]
