# Generated by Django 5.2.7 on 2025-12-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_login_session_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginsession',
            new_name='login_sessi_user_id_ab9963_idx',
            old_name='login_session_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='loginsession',
            new_name='login_sessi_session_f835ba_idx',
            old_name='login_session_session_key_idx',
        ),
    ]
